version: 1.0.{build}
image: Visual Studio 2019

install:
- cmd: >-
    yarn global add vuepress

    yarn add -D @vuepress/plugin-google-analytics
    
build_script:
  - cmd: vuepress build
   
for:   
-
  branches:
    only:
    - master
  
  configuration: Release
  deploy_script:
    - cmd: >-
        mkdir C:\projects\dist\
        
        git clone -q --branch=gh-pages https://github.com/LowlyDBA/expressdb.git C:\projects\dist\
        
        cd C:\projects\dist\
        
        git rm -r * -q
        
        copy C:\projects\expressdb\.vuepress\dist\* C:\projects\dist\
        
        git config --global user.email "john@lowlydba.com" 
        
        git config --global user.name "John M"
        
        git commit -m "deploy github pages" -q
        
        git push 
    
    
-
  branches: 
   except:
     - master

  configuration: Test
