version: 1.0.{build}
image: Visual Studio 2019

install:
- cmd: >-
    yarn global add vuepress

    yarn add -D @vuepress/plugin-google-analytics
    
build_script:
  - cmd: vuepress build
   
for:   
-
  branches:
    only:
    - master
  
  configuration: Release
  deploy_script:
    - cmd: >-
        vuepress build
        mkdir C:\projects\dist\
        copy .vuepress\dist\* C:\projects\dist\
    
    
-
  branches: 
   except:
     - master

  configuration: Test
