version: 1.0.{build}
image: Visual Studio 2019

environment:
  access_token:
    secure: aQ03S2mWlOaOuaT8QBF6dVYG/sb6PgaeUlJ0rijCFs6gN0jxLH7lo0hgDMELamsQ

install:
- cmd: >-
    yarn global add vuepress

    yarn add -D @vuepress/plugin-google-analytics
    
build_script:
  - cmd: vuepress build
   
for:   
-
  branches:
    only:
    - master
  
  configuration: Release
  deploy_script:
    - ps: >-
        mkdir C:\projects\dist\
        
        git clone -q --branch=gh-pages https://github.com/LowlyDBA/expressdb.git C:\projects\dist\
        
        cd C:\projects\dist\
        
        git rm -r "*" -q
        
        copy C:\projects\expressdb\.vuepress\dist\* C:\projects\dist\
        
        git config --global credential.helper store
        
        Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
        
        git config --global user.email "john@lowlydba.com" 
        
        git config --global user.name "John M"
        
        git add .
        
        git commit -a -m "deploy github pages" -q
        
        git push origin gh-pages -f
    
-
  branches: 
   except:
     - master

  configuration: Test
