version: 1.0.{build}
image: Visual Studio 2019

install:
  - cmd: >-
    yarn global add vuepress

    yarn add -D @vuepress/plugin-google-analytics
    
build_script:
  - cmd: vuepress build
    
-
  branches:
    only:
    - master
  
  configuration: Release
  deploy:
    - cmd: vuepress build
    
-
  branches: 
   except:
     - master

  configuration: Test


    


